name: Deploy React App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # downloads code onto the cloud computer

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Sets up Node.js

      - name: Install dependencies
        run: npm install

      - name: Deploy
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatically filled by GitHub
          CI: false